spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: @ddl-auto@
    show-sql: true
  liquibase:
    change-log: db.changelog/db.changelog-master.xml
    enabled: @liquibase.enable@